// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "MFramePart.h"
#include "GeneratorPart.generated.h"

/**
 * 
 */
UCLASS()
class MECHBUILDER_API AGeneratorPart : public AMFramePart
{
	GENERATED_BODY()
	
public:

	// constructor
	AGeneratorPart();

protected:

public:

	// Get the power generated by the generator
	UFUNCTION(BlueprintCallable, Category = "Generator Part")
	int32 GetPowerGenerated();

	// Get the power available after current usage
	UFUNCTION(BlueprintCallable, Category = "Generator Part")
	int32 GetPowerAvailable();

private:

	// Power generated by the generator
	UPROPERTY(EditDefaultsOnly, Category = "Generator Part")
	int32 PowerGenerated = 50;

	// Power left after current usage
	UPROPERTY(VisibleAnywhere, Category = "Generator Part")
	int32 PowerAvailable;

	int32 CalcPowerAvailable(int32 PowerGenerated, int32 PowerUsed);
};
